### ISSUE TITLE
Install fails to bind plugin to OnHandleRequest system event

### ISSUE THREAD

**Issue by pixelchutes** [opengeek/dbapi#5]
When installing DBAPI in MODX 2.3, I ran into an error at the end of installation. It resulted in  an empty system event record in the database, and the plugin was not correctly linked to `OnHandleRequest`.

I had to manually update the DB and create the plugin relationship to get this to work.

I will see if I can find the specific error and post it here.

**Comment by pixelchutes** [comment]
bump! :smile:

Issue marked as resolved, but 1.0.1-pl transport package on MODX website does not contain the necessary fix.

**Comment by opengeek** [comment]
yikes, ok — will look at it shortly

**Comment by pixelchutes** [comment]
Can this issue please be re-opened? At least until v1.0.2-pl is distributed?

**Comment by opengeek** [comment]
Yikes...sorry about this @pixelchutes — will publish now...

**Comment by opengeek** [comment]
https://modx.com/extras/package/dbapi

**Comment by pixelchutes** [comment]
Thank you!!
